package com.bookstore.entity;
// Generated 15 May 2023, 15:47:29 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.Table;
import jakarta.persistence.NamedQueries;

/**
 * Users generated by hbm2java
 */

@Entity
@NamedQueries({
@NamedQuery(name = "Users.findAll", query = "Select u FROM Users u ORDER BY u.fullName"),
@NamedQuery(name = "Users.findByEmail", query = "Select u FROM Users u WHERE u.email = :email"),
@NamedQuery(name = "Users.countAll", query = "SELECT Count(*) FROM Users u"),
@NamedQuery(name = "Users.checkLogin", query = "SELECT u FROM Users u WHERE u.email = :email AND u.password = :password"),
		})
@Table(name = "users", catalog = "bookstoredb")
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String email;
	private String password;
	private String fullName;

	public Users() {
	}
	
	public Users(Integer userId, String email, String password, String fullName) {
		this(email, password, fullName);
		this.userId = userId;
	}

	public Users(String email, String password, String fullName) {
		this.email = email;
		this.password = password;
		this.fullName = fullName;
	}

	@Id
	//@GeneratedValue(strategy = IDENTITY)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", nullable = false, length = 30)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

}
